### PR TITLE
turn-server with static-auth-secret in a separate php script

### PR DESCRIPTION
**Pull request by Jumper78**
This is a new solution to the problem states in #857: if you use a turn-server with static-auth-secret, you need a server based generation of username and password without handing out the secret key. This time, a key is created by a script `turn-credentials.php` in json-form and is processed by `main.js`.

index.html
added a two config-lines that can simply be uncommented for activating the "twilio-mode" or the "php-credentials-mode"

turn-credentials.php (new file)
will generate username and password for a turn server with a static-auth-secret and will offer it in json-format

main.js
added a section that requests output from php-credentials.php and adds the username, password, stun-server and turn-server into the configuration

### CODE REVIEW

**Comment by Jumper78** [comment]
Using `session.turn-mode` as a switch did not work, so I now moved the code directly to `index.html`.

**Comment by saschafoerster** [comment]
@Jumper78 Why was this closed? As it was not integrated? I would also like to have turn with static-auth-secret in VDO Ninja, so I was surprised.

**Comment by steveseguin** [comment]
As per why I never merged it:

PHP is an active server component, where as everything else in the repo is passive HTML/Javascript code. I don't think it would be appropriate to have PHP scripts merged into the main repo. I also didn't want to close the request though, if others thought it would be helpful to have as a reference.

I can still merge if needed, although I'd want to de-activate the PHP script by renaming the extension or such.

**Comment by Jumper78** [comment]
As per why I closed the request:
I just wanted to clean up my open issues. The implementation in here works perfectly for me since more than a year now. Even with the request being closed, it still can work as reference for everyone who wants to implement this.

**Comment by saschafoerster** [comment]
@steveseguin I understand, that you want to keep it "KISS". Until now I couldn't really use VDO Ninja with TURN, as I didn't want to leave my credentials like this on the web server readable by everyone. I also prefered static-auth-secret, as I used it for my Jitsi and BigBlueButton instances. Now I am no programmer or expert in PHP: would this extension solve my problem? So regular uses couldn't read in cleartext my credentials? If yes, I would be really happy if it could be merged, even if it is commented out or renamed as it would make TURN more usable. In daily usage we see a lot of need to use TURN, especially for business customers or public sectors.

**Review by steveseguin — APPROVED** [review]
Thank you. Apologies for not doing this sooner

**Comment by Jumper78** [comment]
> Now I am no programmer or expert in PHP: would this extension solve my problem? So regular uses couldn't read in cleartext my credentials?

Regular users will not be able to see your complete credentials in clear text, yes. But, they will see which address they have to call to get new temporary passwords.
The system works similar to what you might know from Google-Authenticator: there is a key hidden on the server that can be used to generate new temporary keys all the time. Every time someone calls: https://your-server.com/turn-credentials.php, he will get a new username and password for your turn-server that is valid for a defined time (I think, for my turn-server it is in the range of a few hours). Unless you are doing mistakes in the configuration of your webserver, your main key will be protected.
So, this method will prevent the occasional user from using your turn-server but it will not keep someone determined to use your turn-server from constantly requesting new passwords and then use it.

**Pull request merged**
