### PR TITLE
Create CNAME

### PR DESCRIPTION
**Pull request by JeanKha**

### CODE REVIEW

**Comment by jcalado** [comment]
Why are you trying to have this merged?
This makes absolutely no sense.

**Comment by JeanKha** [comment]
> I'm sorry, I'm not a pro and first time using github.

**Comment by jcalado** [comment]
There's no problem, but please do not open "Pull Requests" (PR)  unless you
want to contribute back to the main project.
You can tweak your fork as you will, but only PR stuff that you think
should be in vdo.ninja.

**Comment by steveseguin** [comment]
> > I'm sorry, I'm not a pro and first time using github.

we 100% understand.  All good.   If you need help, feel free to ask on discord.  

-steve

**Comment by JeanKha** [comment]
> > > I'm sorry, I'm not a pro and first time using github.
> 
> we 100% understand. All good. If you need help, feel free to ask on discord.
> 
> -steve

I would like to send my special thanks to Steve, your project helped me with a great remote broadcast solution.

**Pull request closed without merging**
