### PR TITLE
Create iframe.outbound-stats.html

### PR DESCRIPTION
**Pull request by duncanbarnes**
Added an example of using the iFrame API to retrieve and display outgoing viewer stats.

### CODE REVIEW

**Review by steveseguin — APPROVED** [review]

**Comment by steveseguin** [comment]
thank you. I'll give it a go

**Comment by duncanbarnes** [comment]
Afraid it does use jQuery and Bootstrap in there for styling etc, know there are mixed feelings about that generally and that OBSN is not dependant on external libs but thought that for an example case such as this it wasn't as important and makes developing a bit faster (for me!). :-)

**Comment by steveseguin** [comment]
For a sample page, that's fine.  No worries.  :)

**Comment by steveseguin** [comment]
Closing old issue automatically by bot; the iframe outbound-stats example now exists.

**Pull request merged**
