### PR TITLE
Translation for pt-br

### LINKED ISSUE #980: Can we translate for specific countries? e.g. "pt-br"
Hi there, this is an awsome project! I'm looking forward to try out and contribute.

I'd like to know if it only supports generic translation per language ("pt") or if we can create a translation for a specific country ("pt-br")?

And if we can, how should be the filename pattern?

Thanks!

### PR DESCRIPTION
**Pull request by lguima**
- Created a translation file for pt-br.
- I also ordered the keys alphabetically to help finding existing values and avoiding duplication.

Suggested language title/name: "Português (Brasil)".

---
Resolve #980

### CODE REVIEW

**Review by steveseguin — APPROVED** [review]
Looks good. Thank you

**Comment by steveseguin** [comment]
I'll add this to the main deployment and the drop down menu as an option, based on your recommendation previously.

**Comment by lguima** [comment]
Alright, thank you!

**Comment by steveseguin** [comment]
Should be added. Hope it's all okay.

image

**Pull request merged**
