### PR TITLE
"no network connection" alert

### PR DESCRIPTION
**Pull request by jcalado**

### CODE REVIEW

**Review by steveseguin — COMMENTED** [review]
You'll need to respect the session.cleanOutput flag with your alert statement.

**Comment by filiptronicek** [comment]
@steveseguin does this close #601?

**Comment by steveseguin** [comment]
> @steveseguin does this close #601?

Not in full.

I think a modal option is better than a popup, but if people thing a popup is better than nothing, it's a step forward.

As much as I use popups, if they are not expected they can be pretty annoying during a live stream

**Comment by jcalado** [comment]
I like the idea of a modal. I'll have a look at it as well. There's a lot of alert() going on.

**Comment by steveseguin** [comment]
Thank you, both of you.

  Some of the alerts have value, as they stop the code execution and that is needed at times, but others could be replaced by a modal.  An alert popup is universal (mobile friendly), while a modal requires more device testing, so I've avoided it for now.

Happy to discuss some concepts for a modal box that could be reused.

**Pull request merged**
