### PR TITLE
Update README for markdown constistency

### PR DESCRIPTION
**Pull request by filiptronicek**
- Updated some `<h4>` that were direct children of `<h2>`s to `<h3>`
- Removed some unnecessary question marks and other symbols (for it to be consistent everywhere)

### CODE REVIEW

**Review by steveseguin — APPROVED** [review]

**Comment by steveseguin** [comment]
Thank you

**Comment by filiptronicek** [comment]
Also, the two images on the top of the markdown have a canonical URL that points to gyazo.com, which always displays  this same image: 
image
Maybe worth deleting those attributes @steveseguin? Not sure if they are wanted for keeping it for archiving or something.

**Comment by steveseguin** [comment]
fixed. thank you for pointing that out

**Comment by filiptronicek** [comment]
Oops, @steveseguin, looks like that broke the second image
image

**Comment by steveseguin** [comment]
I'm awful, haha. thank you

**Pull request merged**
