### PR TITLE
Ukrainian translation

### PR DESCRIPTION
**Pull request by Arteboy**
Ukrainian translation

### CODE REVIEW

**Review by filiptronicek — CHANGES_REQUESTED** [review]
Hi, thanks for your contribution, if you could, please do the two following things:
1. Stick to the file names in the ISO 639-1 code, which means to change the language name from `ukr` to `uk`. (See [the list](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) for more info)
2. Update the language list in `translate.js`
https://github.com/steveseguin/obsninja/blob/1511de02776b01786dd397bb59b6eb1f878cc6e5/translations/translate.js#L71-L85
3. Please sign the CLA 😄 


If you have any problems feel free to ping me or @steveseguin

**Review by filiptronicek — APPROVED** [review]
Looks good to me ✅

**Comment by Arteboy** [comment]
Sorry guys< my first github.
Changes are made ^)

**Comment by filiptronicek** [comment]
@Arteboy We all had our first, thanks for the quick changes!

**Review by jcalado — APPROVED** [review]

**Comment by jcalado** [comment]
Thanks for contributing @Arteboy!

**Pull request merged**
